title: Woodlands Honey
description: ""
theme: minima

menu_items:
  - name: Home
    link: /
  - name: Our Bees
    link: /#our-bees
  - name: Crystallisation
    link: /#honey-crystallises
  - name: Age Restriction
    link: /#age-restriction
  - name: Extraction
    link: /#about-our-honey-and-its-extraction
  - name: Contacts
    link: /#contact-us
